### ISSUE TITLE
Write a differential decoder for live broadcast captures

### ISSUE THREAD

**Issue by ali1234** [ali1234/vhs-teletext#19]
The deconvolving method used for VHS recordings is not compatible with live broadcasts. They can be decoded much easier and faster with a differential decoder anyway. This could be implemented for completeness. Depends on #17.

**Comment by ChaoticNeutralCzech** [comment]
Thanks. However, the only way to find out what the `--slice` option mentioned in the output of `teletext deconvolve --help` was actually doing without extensive knowledge of the codebase was finding this issue and reading the code from [corresponding commit 9c1a9e5](https://github.com/ali1234/vhs-teletext/commit/9c1a9e5c150add7306fa3fc1e4b4e2242eeb68e5). Please improve the documentation or at least make all the `--help` outputs somewhere online so people can read and comment! See Issue #67.
