### ISSUE TITLE
Cannot deconvolve any data using v2 software

### ISSUE THREAD

**Issue by ZXByteman** [ali1234/vhs-teletext#24]
Hi!

I've tried to perform deconvolution of raw vbi data captured from SAA7231 based capture card. It produces 1440 samples per line without black samples on the right. I've edited config.py file by modifying saa7131 config (1440 instead of 1600 lines), also default "card" type was hardcoded because of "--card" option issue. 
I get no meaningful data in the produced t42 stream, but with "v1" software I was able to decode at least something.

Could you have a look at sample data and help to determine the root cause of no data decoded, and help to "tweak" deconvolve if needed?

Capture card: Behold H8 (SAA7231), 1440 samples per line
VCR: Panasonic AG-4700 (edit mode)
Source: SECAM recording, RTR channel (1995, Russia)
Sample: https://files.byteman.by/vhs-teletext/RTR_1995_SAA7231.zip (about 40 minutes of capture)

Thanks in advance.

**Comment by ali1234** [comment]
Do you mean V3 because V2 doesn't have these options?

**Comment by ZXByteman** [comment]
Sorry, my mistake, I've meant V3, the latest version from repository.

**Comment by ali1234** [comment]
Deconvolution works now but still very low quality output. Probably the sample rate needs to be tweaked. Line detection seems to be working well which is a good start.

**Comment by ZXByteman** [comment]
Do you think it is worth trying to make capture with another capture card? I may have a try with another card based on SAA7136.

**Comment by ali1234** [comment]
I think the problem is that there aren't enough samples before and after the data to get a good noise floor estimate. So probably not.

**Comment by ZXByteman** [comment]
I've uploaded capture from the same source using SAA7136 capture card and the same VCR. Could you help please to determine if this capture is better than from SAA7231 or not?
https://files.byteman.by/vhs-teletext/RTR_1995_SAA7136.zip

Regards,
Alexander

**Comment by ZXByteman** [comment]
Acquired bt878 card
