### ISSUE TITLE
Get rid of CUBLAS warnings

### ISSUE THREAD

**Issue by wimpie3** [ali1234/vhs-teletext#47]
Is it possible to remove the confusing warning 'creating CUBLAS context to get version number'? There is no need to show that message.

**Comment by ali1234** [comment]
This is done by the skcuda library. You can patch it out in cublas.py but I'm not aware of any way to disable it from my side.

**Comment by ali1234** [comment]
Closing this as there isn't anything I can do about it, sorry.
