### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by aloyisus** [ali1234/vhs-teletext#5]
I've just bought an old PCI Hauppauge winTV card (with the 878 chip) to experiment with your software, but I'm getting the following error when I try to deconvolve my VBI capture:

./deconvolve -H -S 20 capture_trunc.vbi > headers.txt
No module named pycuda.driver
CUDA init failed. Using slow CPU method instead.
Traceback (most recent call last):
  File "./deconvolve", line 102, in <module>
    for l_list in split_seq(it, args.squash):
  File "./deconvolve", line 94, in split_seq
    item = list(itertools.islice(it, size))
  File "/home/johnnyk/Documents/dev/vhs-teletext/teletext/vbi/map.py", line 82, in raw_line_map
    for l in map_func(func, raw_line_reader(filename, line_length, start, stop)):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 269, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/johnnyk/Documents/dev/vhs-teletext/teletext/vbi/map.py", line 24, in wrap
    return func(self, timeout=timeout if timeout is not None else 1e100)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
TypeError: slice indices must be integers or None or have an __index__ method

Unfortunately I can't try the newer CUDA method, so I'm forced to use the CPU. Have you seen anything like this before? Possibly my VBI capture is just bad, but I don't know if I need to do any setup for that. I have attached a truncated excerpt of the cap. which reproduces the error.

This is how my card is set up for capture at the moment:
v4l2-ctl -d /dev/vbi0 --get-fmt-vbi
Format VBI Capture:
	Sampling Rate   : 35468950 Hz
	Offset          : 244 samples (6.87926e-06 secs after leading edge)
	Samples per Line: 2048
	Sample Format   : GREY
	Start 1st Field : 7
	Count 1st Field : 16
	Start 2nd Field : 320
	Count 2nd Field : 16

Cheers for any insight you can give, apologies if this is user error.

[capture_trunc.tar.gz](https://github.com/ali1234/vhs-teletext/files/791827/capture_trunc.tar.gz)

John.

**Comment by aloyisus** [comment]
This turned out to be due to a change in numpy 1.12.0 that disallows the use of floats as indices, see the release notes [here](https://github.com/numpy/numpy/blob/master/doc/release/1.12.0-notes.rst). 

Reverting to numpy 1.11.2 made the error go away, and I'm now capturing teletext successfully.

Thanks so much for making this code available, it's awesome :)

Cheers,

John.

**Comment by ali1234** [comment]
This is a bug then. I will fix it some time.

**Comment by ali1234** [comment]
This should be fixed in the new Python 3 port, although maybe because I haven't implemented the feature that caused it yet.
