### ISSUE TITLE
t42 format description

### ISSUE THREAD

**Issue by turlututututu** [ali1234/vhs-teletext#53]
Hi first of all amazing work :)

I am interested in having a dump of Teletext page so that I could see what packets build it and them interpret it by "hand" for debug purposes.

My main goal would be to extract those pages from a ts and then examine it.

The file format .t42 seems to fit my needs but I don't know how it is to be read ? Is there any description of the format?

Thanks in advance!

**Comment by ali1234** [comment]
T42 is just concatenated packets. Each one is 42 bytes, hence the name. The clock run in and framing code are not included as they never change. The packet format is as described in the spec.

**Comment by turlututututu** [comment]
Thank you for your quick response! Could you point me torward the spec? I didn't find it on the repo unless you are talking about ETS and such?

**Comment by ali1234** [comment]
https://www.etsi.org/deliver/etsi_i_ets/300700_300799/300706/01_60/ets_300706e01p.pdf

**Comment by turlututututu** [comment]
Thanks a million!
