### ISSUE TITLE
Name 'celp' is not defined

### ISSUE THREAD

**Issue by jh42** [ali1234/vhs-teletext#80]
I just installed vhs-teletext on a fresh Ubuntu 22.04 system following the User Guide. The install went fine, but attempting to invoke `teletext` (no matter which arguments) results in the following error:

> user@ubuntu:~/vhs-teletext$ teletext
> Traceback (most recent call last):
>   File "/home/user/.local/bin/teletext", line 33, in <module>
>     sys.exit(load_entry_point('teletext', 'console_scripts', 'teletext')())
>   File "/home/user/.local/bin/teletext", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/home/user/vhs-teletext/teletext/cli/teletext.py", line 68, in <module>
>     teletext.add_command(celp)
> NameError: name 'celp' is not defined. Did you mean: 'help'?

Commenting out the line `teletext.add_command(celp)` in cli/teletext.py fixes the crash and record/deconvolve appear to work fine — but of course I don't know what's missing from the program now :)

**Comment by ali1234** [comment]
It means you don't have the libraries for CELP audio decoding. I removed them from the dependencies because they are not easily available on Windows. You probably don't care about CELP. It should not crash if they are not available though, so I have fixed that.

**Comment by ali1234** [comment]
btw there are quite a lot of optional dependencies, see setup.py for the list.
